const ELEMENTS = [
  {
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hidrógeno',
    atomicMass: 1.008,
    category: 'no-metal',
    period: 1,
    group: 1,
    electronConfiguration: '1s¹',
    standardState: 'gas',
    meltingPoint: 13.99,
    boilingPoint: 20.271,
    summary: 'El elemento más abundante en el universo. Gas diatómico a temperatura ambiente, es el combustible de las estrellas por fusión nuclear.'
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helio',
    atomicMass: 4.0026,
    category: 'gas-noble',
    period: 1,
    group: 18,
    electronConfiguration: '1s²',
    standardState: 'gas',
    meltingPoint: null,
    boilingPoint: 4.222,
    summary: 'Gas noble más ligero, segundo elemento más abundante del universo. Tiene el punto de ebullición más bajo de todos los elementos.'
  },
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: 'Litio',
    atomicMass: 6.94,
    category: 'metal-alcalino',
    period: 2,
    group: 1,
    electronConfiguration: '[He] 2s¹',
    standardState: 'solid',
    meltingPoint: 453.65,
    boilingPoint: 1603,
    summary: 'Metal alcalino más ligero, blando y de color plateado. Es fundamental en la fabricación de baterías recargables modernas.'
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: 'Berilio',
    atomicMass: 9.0122,
    category: 'metal-alcalinoterreo',
    period: 2,
    group: 2,
    electronConfiguration: '[He] 2s²',
    standardState: 'solid',
    meltingPoint: 1560,
    boilingPoint: 2742,
    summary: 'Metal ligero, rígido y gris acero. Se usa en aleaciones de alta resistencia y como moderador en reactores nucleares.'
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: 'Boro',
    atomicMass: 10.81,
    category: 'metaloide',
    period: 2,
    group: 13,
    electronConfiguration: '[He] 2s² 2p¹',
    standardState: 'solid',
    meltingPoint: 2349,
    boilingPoint: 4200,
    summary: 'Metaloide con propiedades semiconductoras. Se usa en vidrios borosilicatados, detergentes y como dopante en semiconductores.'
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbono',
    atomicMass: 12.011,
    category: 'no-metal',
    period: 2,
    group: 14,
    electronConfiguration: '[He] 2s² 2p²',
    standardState: 'solid',
    meltingPoint: 3823,
    boilingPoint: 4098,
    summary: 'Base de toda la química orgánica y de la vida. Existe en alótropos como el diamante, el grafito y el grafeno con propiedades muy distintas.'
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: 'Nitrógeno',
    atomicMass: 14.007,
    category: 'no-metal',
    period: 2,
    group: 15,
    electronConfiguration: '[He] 2s² 2p³',
    standardState: 'gas',
    meltingPoint: 63.15,
    boilingPoint: 77.355,
    summary: 'Constituye el 78% de la atmósfera terrestre. Es esencial para la vida al formar parte de aminoácidos, proteínas y ácidos nucleicos.'
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxígeno',
    atomicMass: 15.999,
    category: 'no-metal',
    period: 2,
    group: 16,
    electronConfiguration: '[He] 2s² 2p⁴',
    standardState: 'gas',
    meltingPoint: 54.36,
    boilingPoint: 90.188,
    summary: 'Tercer elemento más abundante del universo, esencial para la respiración celular. Constituye el 21% de la atmósfera y forma parte del agua.'
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: 'Flúor',
    atomicMass: 18.998,
    category: 'halogeno',
    period: 2,
    group: 17,
    electronConfiguration: '[He] 2s² 2p⁵',
    standardState: 'gas',
    meltingPoint: 53.48,
    boilingPoint: 85.03,
    summary: 'El elemento más electronegativo y reactivo de la tabla periódica. Se usa en pastas dentífricas y en la síntesis de polímeros como el teflón.'
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: 'Neón',
    atomicMass: 20.18,
    category: 'gas-noble',
    period: 2,
    group: 18,
    electronConfiguration: '[He] 2s² 2p⁶',
    standardState: 'gas',
    meltingPoint: 24.56,
    boilingPoint: 27.104,
    summary: 'Gas noble con una brillante emisión de luz roja-anaranjada cuando se ioniza. Se usa ampliamente en letreros luminosos y láseres.'
  },
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: 'Sodio',
    atomicMass: 22.99,
    category: 'metal-alcalino',
    period: 3,
    group: 1,
    electronConfiguration: '[Ne] 3s¹',
    standardState: 'solid',
    meltingPoint: 370.944,
    boilingPoint: 1156.09,
    summary: 'Metal alcalino blando y muy reactivo, esencial para la vida. Componente principal de la sal de mesa en forma de cloruro de sodio.'
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: 'Magnesio',
    atomicMass: 24.305,
    category: 'metal-alcalinoterreo',
    period: 3,
    group: 2,
    electronConfiguration: '[Ne] 3s²',
    standardState: 'solid',
    meltingPoint: 923,
    boilingPoint: 1363,
    summary: 'Metal ligero y resistente, cuarto elemento más abundante en la Tierra. Esencial para la clorofila y numerosos procesos enzimáticos en el organismo.'
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: 'Aluminio',
    atomicMass: 26.982,
    category: 'metal-post-transicion',
    period: 3,
    group: 13,
    electronConfiguration: '[Ne] 3s² 3p¹',
    standardState: 'solid',
    meltingPoint: 933.473,
    boilingPoint: 2743,
    summary: 'Metal más abundante de la corteza terrestre, ligero y resistente a la corrosión. Ampliamente usado en envases, construcción y transporte.'
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: 'Silicio',
    atomicMass: 28.085,
    category: 'metaloide',
    period: 3,
    group: 14,
    electronConfiguration: '[Ne] 3s² 3p²',
    standardState: 'solid',
    meltingPoint: 1687,
    boilingPoint: 3538,
    summary: 'Segundo elemento más abundante de la corteza terrestre. Es la base de la industria microelectrónica y de los semiconductores modernos.'
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: 'Fósforo',
    atomicMass: 30.974,
    category: 'no-metal',
    period: 3,
    group: 15,
    electronConfiguration: '[Ne] 3s² 3p³',
    standardState: 'solid',
    meltingPoint: 317.3,
    boilingPoint: 553.7,
    summary: 'Elemento esencial para los seres vivos, componente del ADN, ARN y ATP. Se usa en fertilizantes agrícolas y en la industria química.'
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: 'Azufre',
    atomicMass: 32.06,
    category: 'no-metal',
    period: 3,
    group: 16,
    electronConfiguration: '[Ne] 3s² 3p⁴',
    standardState: 'solid',
    meltingPoint: 388.36,
    boilingPoint: 717.76,
    summary: 'No metal amarillo con olor característico, esencial para las proteínas. Se usa en la producción de ácido sulfúrico y vulcanización del caucho.'
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: 'Cloro',
    atomicMass: 35.45,
    category: 'halogeno',
    period: 3,
    group: 17,
    electronConfiguration: '[Ne] 3s² 3p⁵',
    standardState: 'gas',
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    summary: 'Gas halógeno amarillo-verdoso con propiedades desinfectantes. Se usa en el tratamiento del agua potable y en la síntesis de compuestos orgánicos.'
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: 'Argón',
    atomicMass: 39.948,
    category: 'gas-noble',
    period: 3,
    group: 18,
    electronConfiguration: '[Ne] 3s² 3p⁶',
    standardState: 'gas',
    meltingPoint: 83.81,
    boilingPoint: 87.302,
    summary: 'Gas noble más abundante de la atmósfera terrestre (0,93%). Se usa como gas inerte en soldadura, iluminación y conservación de documentos.'
  },
  {
    atomicNumber: 19,
    symbol: 'K',
    name: 'Potasio',
    atomicMass: 39.098,
    category: 'metal-alcalino',
    period: 4,
    group: 1,
    electronConfiguration: '[Ar] 4s¹',
    standardState: 'solid',
    meltingPoint: 336.7,
    boilingPoint: 1032,
    summary: 'Metal alcalino esencial para la vida, regula el equilibrio hídrico celular y la función nerviosa. Componente clave de los fertilizantes agrícolas.'
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: 'Calcio',
    atomicMass: 40.078,
    category: 'metal-alcalinoterreo',
    period: 4,
    group: 2,
    electronConfiguration: '[Ar] 4s²',
    standardState: 'solid',
    meltingPoint: 1115,
    boilingPoint: 1757,
    summary: 'Quinto elemento más abundante de la corteza terrestre y esencial para los huesos y dientes. Interviene en la contracción muscular y la coagulación sanguínea.'
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: 'Escandio',
    atomicMass: 44.956,
    category: 'metal-transicion',
    period: 4,
    group: 3,
    electronConfiguration: '[Ar] 3d¹ 4s²',
    standardState: 'solid',
    meltingPoint: 1814,
    boilingPoint: 3109,
    summary: 'Metal de transición ligero y plateado. Se usa en aleaciones de aluminio de alta resistencia y en lámparas de halogenuros metálicos.'
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: 'Titanio',
    atomicMass: 47.867,
    category: 'metal-transicion',
    period: 4,
    group: 4,
    electronConfiguration: '[Ar] 3d² 4s²',
    standardState: 'solid',
    meltingPoint: 1941,
    boilingPoint: 3560,
    summary: 'Metal resistente, ligero y biocompatible, altamente resistente a la corrosión. Ampliamente usado en aeronáutica, implantes médicos y arquitectura.'
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: 'Vanadio',
    atomicMass: 50.942,
    category: 'metal-transicion',
    period: 4,
    group: 5,
    electronConfiguration: '[Ar] 3d³ 4s²',
    standardState: 'solid',
    meltingPoint: 2183,
    boilingPoint: 3680,
    summary: 'Metal de transición duro y plateado. Se usa principalmente en aleaciones de acero para aumentar su resistencia y en catálisis química.'
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: 'Cromo',
    atomicMass: 51.996,
    category: 'metal-transicion',
    period: 4,
    group: 6,
    electronConfiguration: '[Ar] 3d⁵ 4s¹',
    standardState: 'solid',
    meltingPoint: 2180,
    boilingPoint: 2944,
    summary: 'Metal duro y brillante, altamente resistente a la corrosión. Componente esencial del acero inoxidable y usado en recubrimientos decorativos y protectores.'
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: 'Manganeso',
    atomicMass: 54.938,
    category: 'metal-transicion',
    period: 4,
    group: 7,
    electronConfiguration: '[Ar] 3d⁵ 4s²',
    standardState: 'solid',
    meltingPoint: 1519,
    boilingPoint: 2334,
    summary: 'Metal de transición esencial para la producción de acero. También es un micronutriente biológico importante para el metabolismo y la formación ósea.'
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Hierro',
    atomicMass: 55.845,
    category: 'metal-transicion',
    period: 4,
    group: 8,
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    standardState: 'solid',
    meltingPoint: 1811,
    boilingPoint: 3134,
    summary: 'Metal más usado por la humanidad, base de la industria del acero. Esencial para el transporte de oxígeno en la sangre a través de la hemoglobina.'
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: 'Cobalto',
    atomicMass: 58.933,
    category: 'metal-transicion',
    period: 4,
    group: 9,
    electronConfiguration: '[Ar] 3d⁷ 4s²',
    standardState: 'solid',
    meltingPoint: 1768,
    boilingPoint: 3143,
    summary: 'Metal magnético de color azul-grisáceo. Se usa en superaleaciones, baterías de ion-litio, pigmentos azules y en medicina nuclear.'
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: 'Níquel',
    atomicMass: 58.693,
    category: 'metal-transicion',
    period: 4,
    group: 10,
    electronConfiguration: '[Ar] 3d⁸ 4s²',
    standardState: 'solid',
    meltingPoint: 1728,
    boilingPoint: 3186,
    summary: 'Metal duro, maleable y resistente a la corrosión. Ampliamente usado en aceros inoxidables, monedas, baterías y recubrimientos industriales.'
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Cobre',
    atomicMass: 63.546,
    category: 'metal-transicion',
    period: 4,
    group: 11,
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    standardState: 'solid',
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    summary: 'Metal rojizo con excelente conductividad eléctrica y térmica. Ha sido utilizado por la humanidad durante milenios en herramientas, monedas y cables eléctricos.'
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicMass: 65.38,
    category: 'metal-transicion',
    period: 4,
    group: 12,
    electronConfiguration: '[Ar] 3d¹⁰ 4s²',
    standardState: 'solid',
    meltingPoint: 692.68,
    boilingPoint: 1180,
    summary: 'Metal azulado esencial para el sistema inmunitario. Se usa en galvanización del acero para prevenir la corrosión y en numerosas aleaciones como el latón.'
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: 'Galio',
    atomicMass: 69.723,
    category: 'metal-post-transicion',
    period: 4,
    group: 13,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹',
    standardState: 'solid',
    meltingPoint: 302.91,
    boilingPoint: 2673,
    summary: 'Metal de bajo punto de fusión que se licúa a temperatura ambiente. Se usa en semiconductores, LED, paneles solares y termómetros de alta temperatura.'
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: 'Germanio',
    atomicMass: 72.63,
    category: 'metaloide',
    period: 4,
    group: 14,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²',
    standardState: 'solid',
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    summary: 'Metaloide predicho por Mendeleev antes de su descubrimiento. Se usa en fibra óptica, semiconductores, detectores de rayos gamma y lentes infrarrojas.'
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: 'Arsénico',
    atomicMass: 74.922,
    category: 'metaloide',
    period: 4,
    group: 15,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³',
    standardState: 'solid',
    meltingPoint: 1090,
    boilingPoint: 887,
    summary: 'Metaloide tóxico conocido desde la antigüedad. Se usa como dopante en semiconductores y en el tratamiento de ciertas enfermedades parasitarias.'
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: 'Selenio',
    atomicMass: 78.971,
    category: 'no-metal',
    period: 4,
    group: 16,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    standardState: 'solid',
    meltingPoint: 494,
    boilingPoint: 958,
    summary: 'No metal semiconductor con propiedades fotovoltaicas. Es un micronutriente esencial con propiedades antioxidantes, usado también en células solares y fotocopiadoras.'
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: 'Bromo',
    atomicMass: 79.904,
    category: 'halogeno',
    period: 4,
    group: 17,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    standardState: 'liquid',
    meltingPoint: 265.8,
    boilingPoint: 332,
    summary: 'Uno de los dos únicos elementos líquidos a temperatura ambiente, de color rojo-marrón y olor fuerte. Se usa en retardantes de llama, agroquímicos y medicamentos.'
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: 'Kriptón',
    atomicMass: 83.798,
    category: 'gas-noble',
    period: 4,
    group: 18,
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    standardState: 'gas',
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    summary: 'Gas noble incoloro e inodoro. Se usa en lámparas de flash fotográfico, láseres y como estándar para la definición del metro (históricamente).'
  },
  {
    atomicNumber: 37,
    symbol: 'Rb',
    name: 'Rubidio',
    atomicMass: 85.468,
    category: 'metal-alcalino',
    period: 5,
    group: 1,
    electronConfiguration: '[Kr] 5s¹',
    standardState: 'solid',
    meltingPoint: 312.45,
    boilingPoint: 961,
    summary: 'Metal alcalino blando, plateado y muy reactivo con el agua. Se usa en relojes atómicos de alta precisión y en investigación de física cuántica.'
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    name: 'Estroncio',
    atomicMass: 87.62,
    category: 'metal-alcalinoterreo',
    period: 5,
    group: 2,
    electronConfiguration: '[Kr] 5s²',
    standardState: 'solid',
    meltingPoint: 1050,
    boilingPoint: 1655,
    summary: 'Metal alcalinotérreo plateado. Sus sales producen llamas de color rojo carmesí en fuegos artificiales, y el isótopo Sr-90 es un subproducto radiactivo nuclear peligroso.'
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    name: 'Itrio',
    atomicMass: 88.906,
    category: 'metal-transicion',
    period: 5,
    group: 3,
    electronConfiguration: '[Kr] 4d¹ 5s²',
    standardState: 'solid',
    meltingPoint: 1799,
    boilingPoint: 3609,
    summary: 'Metal de transición plateado. Se usa en superconductores de alta temperatura, fósforos para pantallas LED y como aditivo en aleaciones de aluminio y magnesio.'
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    name: 'Circonio',
    atomicMass: 91.224,
    category: 'metal-transicion',
    period: 5,
    group: 4,
    electronConfiguration: '[Kr] 4d² 5s²',
    standardState: 'solid',
    meltingPoint: 2128,
    boilingPoint: 4682,
    summary: 'Metal resistente a la corrosión con baja absorción de neutrones. Ampliamente usado en las vainas de combustible de reactores nucleares y en cerámica de alta tecnología.'
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    name: 'Niobio',
    atomicMass: 92.906,
    category: 'metal-transicion',
    period: 5,
    group: 5,
    electronConfiguration: '[Kr] 4d⁴ 5s¹',
    standardState: 'solid',
    meltingPoint: 2750,
    boilingPoint: 5017,
    summary: 'Metal dúctil y de color gris acerado. Se usa principalmente como aditivo en aceros de alta resistencia y en aplicaciones superconductoras a bajas temperaturas.'
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    name: 'Molibdeno',
    atomicMass: 95.95,
    category: 'metal-transicion',
    period: 5,
    group: 6,
    electronConfiguration: '[Kr] 4d⁵ 5s¹',
    standardState: 'solid',
    meltingPoint: 2896,
    boilingPoint: 4912,
    summary: 'Metal refractario con uno de los puntos de fusión más altos. Esencial como micronutriente en la fijación del nitrógeno biológico y ampliamente usado en aceros especiales.'
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    name: 'Tecnecio',
    atomicMass: 97,
    category: 'metal-transicion',
    period: 5,
    group: 7,
    electronConfiguration: '[Kr] 4d⁵ 5s²',
    standardState: 'solid',
    meltingPoint: 2430,
    boilingPoint: 4538,
    summary: 'Primer elemento producido artificialmente, no existe de forma estable en la naturaleza. Su isótopo Tc-99m es el radiotrazador más usado en medicina nuclear diagnóstica.'
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    name: 'Rutenio',
    atomicMass: 101.07,
    category: 'metal-transicion',
    period: 5,
    group: 8,
    electronConfiguration: '[Kr] 4d⁷ 5s¹',
    standardState: 'solid',
    meltingPoint: 2607,
    boilingPoint: 4423,
    summary: 'Metal del grupo del platino, duro y resistente a la corrosión. Se usa como catalizador en síntesis química, en electrónica y para endurecer aleaciones de platino y paladio.'
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    name: 'Rodio',
    atomicMass: 102.91,
    category: 'metal-transicion',
    period: 5,
    group: 9,
    electronConfiguration: '[Kr] 4d⁸ 5s¹',
    standardState: 'solid',
    meltingPoint: 2237,
    boilingPoint: 3968,
    summary: 'Metal precioso del grupo del platino, muy brillante y resistente. Principal uso en catalizadores de convertidores catalíticos de automóviles para reducir emisiones contaminantes.'
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    name: 'Paladio',
    atomicMass: 106.42,
    category: 'metal-transicion',
    period: 5,
    group: 10,
    electronConfiguration: '[Kr] 4d¹⁰',
    standardState: 'solid',
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    summary: 'Metal precioso plateado con notable capacidad de absorber hidrógeno. Se usa en catalizadores, electrónica, odontología y como alternativa al platino en joyería.'
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    name: 'Plata',
    atomicMass: 107.87,
    category: 'metal-transicion',
    period: 5,
    group: 11,
    electronConfiguration: '[Kr] 4d¹⁰ 5s¹',
    standardState: 'solid',
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    summary: 'Metal precioso con la mayor conductividad eléctrica y térmica de todos los elementos. Apreciado en joyería, fotografía tradicional, electrónica y por sus propiedades antimicrobianas.'
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    name: 'Cadmio',
    atomicMass: 112.41,
    category: 'metal-transicion',
    period: 5,
    group: 12,
    electronConfiguration: '[Kr] 4d¹⁰ 5s²',
    standardState: 'solid',
    meltingPoint: 594.22,
    boilingPoint: 1040,
    summary: 'Metal tóxico de color blanco-azulado. Se usa en baterías de níquel-cadmio, recubrimientos anticorrosión y como pigmento, aunque su uso está restringido por su toxicidad.'
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    name: 'Indio',
    atomicMass: 114.82,
    category: 'metal-post-transicion',
    period: 5,
    group: 13,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p¹',
    standardState: 'solid',
    meltingPoint: 429.75,
    boilingPoint: 2345,
    summary: 'Metal blando, plateado y muy maleable. Su principal aplicación es en el óxido de indio y estaño (ITO), transparente y conductor, usado en pantallas táctiles y LCD.'
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    name: 'Estaño',
    atomicMass: 118.71,
    category: 'metal-post-transicion',
    period: 5,
    group: 14,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p²',
    standardState: 'solid',
    meltingPoint: 505.08,
    boilingPoint: 2875,
    summary: 'Metal blando y plateado conocido desde la antigüedad. Se usa en soldaduras electrónicas, revestimiento de latas de conserva y en la fabricación del bronce con cobre.'
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    name: 'Antimonio',
    atomicMass: 121.76,
    category: 'metaloide',
    period: 5,
    group: 15,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p³',
    standardState: 'solid',
    meltingPoint: 903.78,
    boilingPoint: 1908,
    summary: 'Metaloide brillante de color plateado azulado. Se usa en aleaciones para baterías de plomo-ácido, retardantes de llama y en semiconductores de la industria electrónica.'
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    name: 'Teluro',
    atomicMass: 127.6,
    category: 'metaloide',
    period: 5,
    group: 16,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁴',
    standardState: 'solid',
    meltingPoint: 722.66,
    boilingPoint: 1261,
    summary: 'Metaloide semiconductor de color plateado. Se usa en paneles solares de telururo de cadmio, aleaciones de acero y como pigmento en vidrios y cerámicas.'
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    name: 'Yodo',
    atomicMass: 126.9,
    category: 'halogeno',
    period: 5,
    group: 17,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁵',
    standardState: 'solid',
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    summary: 'Halógeno sólido que sublima a vapor violáceo a temperatura ambiente. Esencial para la síntesis de hormonas tiroideas, y sus compuestos se usan como antisépticos y en fotografía.'
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    name: 'Xenón',
    atomicMass: 131.29,
    category: 'gas-noble',
    period: 5,
    group: 18,
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁶',
    standardState: 'gas',
    meltingPoint: 161.4,
    boilingPoint: 165.051,
    summary: 'Gas noble pesado y muy escaso en la atmósfera. Se usa en lámparas de alta intensidad, láseres de excímero, propulsión de satélites y como agente anestésico.'
  },
  {
    atomicNumber: 55,
    symbol: 'Cs',
    name: 'Cesio',
    atomicMass: 132.91,
    category: 'metal-alcalino',
    period: 6,
    group: 1,
    electronConfiguration: '[Xe] 6s¹',
    standardState: 'solid',
    meltingPoint: 301.7,
    boilingPoint: 944,
    summary: 'Metal alcalino dorado, uno de los metales más blandos y reactivos. Su isótopo Cs-133 es la base de los relojes atómicos que definen el segundo internacional.'
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    name: 'Bario',
    atomicMass: 137.33,
    category: 'metal-alcalinoterreo',
    period: 6,
    group: 2,
    electronConfiguration: '[Xe] 6s²',
    standardState: 'solid',
    meltingPoint: 1000,
    boilingPoint: 2118,
    summary: 'Metal alcalinotérreo plateado. El sulfato de bario se usa como contraste en radiografías gastrointestinales, y sus compuestos producen llamas verdes en pirotecnia.'
  },
  {
    atomicNumber: 57,
    symbol: 'La',
    name: 'Lantano',
    atomicMass: 138.91,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 5d¹ 6s²',
    standardState: 'solid',
    meltingPoint: 1193,
    boilingPoint: 3737,
    summary: 'Primer elemento de las tierras raras, metal plateado y maleable. Se usa en óptica de alta gama, baterías de hidruro metálico de níquel y catalizadores de refinería.'
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    name: 'Cerio',
    atomicMass: 140.12,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f¹ 5d¹ 6s²',
    standardState: 'solid',
    meltingPoint: 1068,
    boilingPoint: 3716,
    summary: 'El lantánido más abundante. Se usa en piedras de mechero, pulimentos de vidrio óptico, catalizadores de automóviles y como componente del acero de alta resistencia.'
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    name: 'Praseodimio',
    atomicMass: 140.91,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f³ 6s²',
    standardState: 'solid',
    meltingPoint: 1208,
    boilingPoint: 3793,
    summary: 'Metal de tierra rara de color amarillo-verdoso. Se usa en potentes imanes permanentes, lentes de vidrio didimio para soldadores y como colorante en cerámicas.'
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    name: 'Neodimio',
    atomicMass: 144.24,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f⁴ 6s²',
    standardState: 'solid',
    meltingPoint: 1297,
    boilingPoint: 3347,
    summary: 'Componente clave de los imanes de neodimio, los más potentes permanentes conocidos. Esencial en motores eléctricos, turbinas eólicas y dispositivos electrónicos modernos.'
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    name: 'Prometio',
    atomicMass: 145,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f⁵ 6s²',
    standardState: 'solid',
    meltingPoint: 1315,
    boilingPoint: 3273,
    summary: 'Único lantánido sin isótopos estables, producido artificialmente. Fue el último lantánido en ser descubierto; sus aplicaciones incluyen fuentes de radiación beta y dispositivos de medición.'
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    name: 'Samario',
    atomicMass: 150.36,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f⁶ 6s²',
    standardState: 'solid',
    meltingPoint: 1345,
    boilingPoint: 2173,
    summary: 'Metal de tierra rara usado en imanes de samario-cobalto, resistentes a altas temperaturas. También se emplea en reactores nucleares como absorbente de neutrones.'
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    name: 'Europio',
    atomicMass: 151.96,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f⁷ 6s²',
    standardState: 'solid',
    meltingPoint: 1099,
    boilingPoint: 1802,
    summary: 'Lantánido con fuertes propiedades de luminiscencia. Se usa como fósforo rojo y azul en pantallas de televisión y en los marcadores fluorescentes de los billetes de euro.'
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    name: 'Gadolinio',
    atomicMass: 157.25,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f⁷ 5d¹ 6s²',
    standardState: 'solid',
    meltingPoint: 1585,
    boilingPoint: 3546,
    summary: 'Lantánido con la mayor sección eficaz para la captura de neutrones térmicos. Muy usado como agente de contraste en resonancias magnéticas (MRI) en medicina diagnóstica.'
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    name: 'Terbio',
    atomicMass: 158.93,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f⁹ 6s²',
    standardState: 'solid',
    meltingPoint: 1629,
    boilingPoint: 3503,
    summary: 'Metal de tierra rara plateado y maleable. Se usa en fósforos verdes para pantallas de color, en dispositivos de almacenamiento magneto-óptico y en lámparas fluorescentes de alta eficiencia.'
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    name: 'Disprosio',
    atomicMass: 162.5,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f¹⁰ 6s²',
    standardState: 'solid',
    meltingPoint: 1680,
    boilingPoint: 2840,
    summary: 'Metal de tierra rara crucial para los imanes de neodimio en aplicaciones de alta temperatura. Se usa en vehículos eléctricos, turbinas eólicas y como absorbente en reactores nucleares.'
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    name: 'Holmio',
    atomicMass: 164.93,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f¹¹ 6s²',
    standardState: 'solid',
    meltingPoint: 1734,
    boilingPoint: 2873,
    summary: 'Lantánido con las propiedades magnéticas más altas de cualquier elemento natural. Se usa en láseres médicos para cirugía mínimamente invasiva y en polos magnéticos especializados.'
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    name: 'Erbio',
    atomicMass: 167.26,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f¹² 6s²',
    standardState: 'solid',
    meltingPoint: 1802,
    boilingPoint: 3141,
    summary: 'Metal de tierra rara de color rosado en sus sales. Esencial en amplificadores de fibra óptica dopada con erbio (EDFA) que permiten las comunicaciones de internet de larga distancia.'
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    name: 'Tulio',
    atomicMass: 168.93,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f¹³ 6s²',
    standardState: 'solid',
    meltingPoint: 1818,
    boilingPoint: 2223,
    summary: 'El lantánido menos abundante en la naturaleza. Se usa en láseres médicos e industriales, en fuentes portátiles de rayos X y como activador en fósforos de aluminato.'
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    name: 'Iterbio',
    atomicMass: 173.05,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f¹⁴ 6s²',
    standardState: 'solid',
    meltingPoint: 1097,
    boilingPoint: 1469,
    summary: 'Lantánido plateado y maleable con un punto de fusión relativamente bajo. Se usa en relojes atómicos de la siguiente generación, láseres de fibra y como dopante en aceros de alta resistencia.'
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    name: 'Lutecio',
    atomicMass: 174.97,
    category: 'lantanido',
    period: 6,
    group: null,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹ 6s²',
    standardState: 'solid',
    meltingPoint: 1925,
    boilingPoint: 3675,
    summary: 'El último y más denso de los lantánidos. Se usa en escintiladores para tomografía PET, como catalizador en procesos de refinería y en aleaciones de alta tecnología.'
  },
  {
    atomicNumber: 72,
    symbol: 'Hf',
    name: 'Hafnio',
    atomicMass: 178.49,
    category: 'metal-transicion',
    period: 6,
    group: 4,
    electronConfiguration: '[Xe] 4f¹⁴ 5d² 6s²',
    standardState: 'solid',
    meltingPoint: 2506,
    boilingPoint: 4876,
    summary: 'Metal resistente a altas temperaturas y de alta absorción de neutrones. Se usa en barras de control de reactores nucleares, superaleaciones para turbinas y en microprocesadores modernos.'
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    name: 'Tántalo',
    atomicMass: 180.95,
    category: 'metal-transicion',
    period: 6,
    group: 5,
    electronConfiguration: '[Xe] 4f¹⁴ 5d³ 6s²',
    standardState: 'solid',
    meltingPoint: 3290,
    boilingPoint: 5731,
    summary: 'Metal refractario muy resistente a la corrosión y biocompatible. Se usa en condensadores electrolíticos de alta capacidad, implantes quirúrgicos e instrumentos de corte de alta dureza.'
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    name: 'Wolframio',
    atomicMass: 183.84,
    category: 'metal-transicion',
    period: 6,
    group: 6,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    standardState: 'solid',
    meltingPoint: 3695,
    boilingPoint: 6203,
    summary: 'Metal con el punto de fusión más alto de todos los elementos (3422 °C). Se usa en filamentos de bombillas incandescentes, electrodos de soldadura y carburo de wolframio para herramientas de corte.'
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    name: 'Renio',
    atomicMass: 186.21,
    category: 'metal-transicion',
    period: 6,
    group: 7,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    standardState: 'solid',
    meltingPoint: 3459,
    boilingPoint: 5903,
    summary: 'Uno de los metales más raros y de mayor punto de fusión. Se usa en superaleaciones para motores de reactores a chorro, catalizadores de reformado de petróleo y termopares de alta temperatura.'
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    name: 'Osmio',
    atomicMass: 190.23,
    category: 'metal-transicion',
    period: 6,
    group: 8,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    standardState: 'solid',
    meltingPoint: 3306,
    boilingPoint: 5285,
    summary: 'El elemento más denso conocido (22,59 g/cm³), de color azul plateado. Se usa en aleaciones para puntas de plumas estilográficas, instrumentos quirúrgicos y como catalizador.'
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    name: 'Iridio',
    atomicMass: 192.22,
    category: 'metal-transicion',
    period: 6,
    group: 9,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    standardState: 'solid',
    meltingPoint: 2719,
    boilingPoint: 4403,
    summary: 'El metal más resistente a la corrosión, de color blanco plateado. Se usa en el prototipo internacional del kilogramo, bujías de alto rendimiento y en implantes médicos de larga duración.'
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    name: 'Platino',
    atomicMass: 195.08,
    category: 'metal-transicion',
    period: 6,
    group: 10,
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    standardState: 'solid',
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    summary: 'Metal precioso de color blanco plateado, muy resistente a la corrosión y excelente catalizador. Se usa en convertidores catalíticos, joyería, electrónica y en quimioterapia anticancerosa.'
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    name: 'Oro',
    atomicMass: 196.97,
    category: 'metal-transicion',
    period: 6,
    group: 11,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    standardState: 'solid',
    meltingPoint: 1337.33,
    boilingPoint: 3243,
    summary: 'Metal precioso amarillo brillante, símbolo de riqueza a lo largo de la historia humana. Excelente conductor eléctrico e inerte químicamente, se usa en joyería, electrónica y como reserva monetaria.'
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    name: 'Mercurio',
    atomicMass: 200.59,
    category: 'metal-transicion',
    period: 6,
    group: 12,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    standardState: 'liquid',
    meltingPoint: 234.321,
    boilingPoint: 629.88,
    summary: 'El único metal líquido a temperatura ambiente, conocido desde la antigüedad como "azogue". Aunque muy tóxico, se usa en termómetros, barómetros, lámparas fluorescentes y en amalgamas dentales.'
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    name: 'Talio',
    atomicMass: 204.38,
    category: 'metal-post-transicion',
    period: 6,
    group: 13,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    standardState: 'solid',
    meltingPoint: 577,
    boilingPoint: 1746,
    summary: 'Metal blando, maleable y muy tóxico. Usado históricamente como veneno de ratas y pesticida; actualmente sus aplicaciones incluyen detectores de radiación infrarroja y electrónica especializada.'
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    name: 'Plomo',
    atomicMass: 207.2,
    category: 'metal-post-transicion',
    period: 6,
    group: 14,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    standardState: 'solid',
    meltingPoint: 600.61,
    boilingPoint: 2022,
    summary: 'Metal pesado, blando y tóxico conocido y usado desde la antigüedad. A pesar de su toxicidad, sigue siendo esencial en baterías de ácido de plomo, blindajes contra radiación y municiones.'
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    name: 'Bismuto',
    atomicMass: 208.98,
    category: 'metal-post-transicion',
    period: 6,
    group: 15,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    standardState: 'solid',
    meltingPoint: 544.7,
    boilingPoint: 1837,
    summary: 'Metal pesado de color blanco rosado con iridiscencia característica en sus óxidos. Considerado prácticamente no tóxico, se usa en medicamentos gastrointestinales, aleaciones de bajo punto de fusión y cosmética.'
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    name: 'Polonio',
    atomicMass: 209,
    category: 'metaloide',
    period: 6,
    group: 16,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    standardState: 'solid',
    meltingPoint: 527,
    boilingPoint: 1235,
    summary: 'Elemento altamente radiactivo descubierto por Marie Curie. Emite partículas alfa intensamente y se usa en dispositivos antiestáticos industriales y como fuente de calor en algunos satélites.'
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    name: 'Ástato',
    atomicMass: 210,
    category: 'metaloide',
    period: 6,
    group: 17,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    standardState: 'solid',
    meltingPoint: 575,
    boilingPoint: 610,
    summary: 'El elemento natural más escaso en la corteza terrestre, altamente radiactivo. Se investiga su isótopo At-211 para radioterapia selectiva de tumores cancerosos mediante terapia alfatargeting.'
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    name: 'Radón',
    atomicMass: 222,
    category: 'gas-noble',
    period: 6,
    group: 18,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    standardState: 'gas',
    meltingPoint: 202,
    boilingPoint: 211.5,
    summary: 'Gas noble radiactivo y sin color, producido por la desintegración del radio. Es un riesgo para la salud en edificios con suelos de granito, siendo la segunda causa de cáncer de pulmón después del tabaco.'
  },
  {
    atomicNumber: 87,
    symbol: 'Fr',
    name: 'Francio',
    atomicMass: 223,
    category: 'metal-alcalino',
    period: 7,
    group: 1,
    electronConfiguration: '[Rn] 7s¹',
    standardState: 'solid',
    meltingPoint: 300,
    boilingPoint: 950,
    summary: 'El metal alcalino más pesado y el segundo elemento más escaso en la naturaleza. Altamente radiactivo con una vida media muy corta; tiene pocas aplicaciones prácticas fuera de la investigación fundamental.'
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    name: 'Radio',
    atomicMass: 226,
    category: 'metal-alcalinoterreo',
    period: 7,
    group: 2,
    electronConfiguration: '[Rn] 7s²',
    standardState: 'solid',
    meltingPoint: 973,
    boilingPoint: 2010,
    summary: 'Metal alcalinotérreo altamente radiactivo descubierto por Marie y Pierre Curie en 1898. Usado históricamente en pinturas luminosas y medicina, ahora reemplazado por isótopos más seguros.'
  },
  {
    atomicNumber: 89,
    symbol: 'Ac',
    name: 'Actinio',
    atomicMass: 227,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 6d¹ 7s²',
    standardState: 'solid',
    meltingPoint: 1500,
    boilingPoint: 3500,
    summary: 'Primer elemento de la serie de los actínidos, altamente radiactivo y de color plateado. Se usa en generadores de neutrones y se investiga su isótopo Ac-225 para tratamientos oncológicos.'
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    name: 'Torio',
    atomicMass: 232.04,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 6d² 7s²',
    standardState: 'solid',
    meltingPoint: 2023,
    boilingPoint: 5061,
    summary: 'Actínido débilmente radiactivo, más abundante que el uranio en la corteza terrestre. Se estudia como combustible alternativo para reactores nucleares de nueva generación por su mayor disponibilidad y seguridad.'
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    name: 'Protactinio',
    atomicMass: 231.04,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f² 6d¹ 7s²',
    standardState: 'solid',
    meltingPoint: 1841,
    boilingPoint: 4300,
    summary: 'Actínido radiactivo y extremadamente escaso en la naturaleza. Es un producto intermedio en la desintegración del uranio-235 y tiene aplicaciones limitadas principalmente en investigación nuclear.'
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    name: 'Uranio',
    atomicMass: 238.03,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f³ 6d¹ 7s²',
    standardState: 'solid',
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    summary: 'El actínido más conocido y la base del combustible nuclear. Su isótopo U-235 es fisible y se usa en reactores nucleares y armas atómicas; el U-238 se emplea en blindajes densos.'
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    name: 'Neptunio',
    atomicMass: 237,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f⁴ 6d¹ 7s²',
    standardState: 'solid',
    meltingPoint: 917,
    boilingPoint: 4273,
    summary: 'Primer elemento transuránico sintetizado artificialmente. Se produce en reactores nucleares y es un precursor en la producción de plutonio-238 usado en generadores radioisotópicos de satélites.'
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    name: 'Plutonio',
    atomicMass: 244,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f⁶ 7s²',
    standardState: 'solid',
    meltingPoint: 912.5,
    boilingPoint: 3505,
    summary: 'Actínido fisible esencial en armas nucleares y reactores de neutrones rápidos. Su isótopo Pu-238 se usa como fuente de energía en sondas espaciales como las misiones Voyager y New Horizons.'
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    name: 'Americio',
    atomicMass: 243,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f⁷ 7s²',
    standardState: 'solid',
    meltingPoint: 1449,
    boilingPoint: 2880,
    summary: 'Actínido sintético ampliamente conocido por su uso cotidiano en detectores de humo iónicos. Su pequeña fuente de Am-241 ioniza el aire para detectar partículas de combustión.'
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    name: 'Curio',
    atomicMass: 247,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f⁷ 6d¹ 7s²',
    standardState: 'solid',
    meltingPoint: 1613,
    boilingPoint: 3383,
    summary: 'Actínido radiactivo bautizado en honor a Marie y Pierre Curie. Se usa como fuente de energía en generadores de radioisótopos y como fuente de partículas alfa en instrumentos científicos.'
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    name: 'Berkelio',
    atomicMass: 247,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f⁹ 7s²',
    standardState: 'solid',
    meltingPoint: 1259,
    boilingPoint: null,
    summary: 'Actínido sintético producido en cantidades muy pequeñas en aceleradores de partículas. Su principal uso es como material de blanco para sintetizar elementos superpesados como el Ts (117).'
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    name: 'Californio',
    atomicMass: 251,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f¹⁰ 7s²',
    standardState: 'solid',
    meltingPoint: 1173,
    boilingPoint: null,
    summary: 'Actínido sintético que emite neutrones de forma espontánea. Se usa en radiografía de neutrones para detectar fracturas en metales, en el arranque de reactores nucleares y para tratar tumores cerebrales resistentes.'
  },
  {
    atomicNumber: 99,
    symbol: 'Es',
    name: 'Einstenio',
    atomicMass: 252,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f¹¹ 7s²',
    standardState: 'solid',
    meltingPoint: 1133,
    boilingPoint: null,
    summary: 'Actínido sintético descubierto en los restos de la primera prueba termonuclear en 1952. Solo se produce en cantidades de microgramos y se usa exclusivamente en investigación científica básica.'
  },
  {
    atomicNumber: 100,
    symbol: 'Fm',
    name: 'Fermio',
    atomicMass: 257,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f¹² 7s²',
    standardState: 'solid',
    meltingPoint: 1800,
    boilingPoint: null,
    summary: 'Actínido sintético también descubierto en los residuos de la primera prueba termonuclear. Su producción es extremadamente difícil y limitada a picogramos; su única aplicación es la investigación nuclear fundamental.'
  },
  {
    atomicNumber: 101,
    symbol: 'Md',
    name: 'Mendelevio',
    atomicMass: 258,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f¹³ 7s²',
    standardState: 'solid',
    meltingPoint: 1100,
    boilingPoint: null,
    summary: 'Actínido sintético bautizado en honor a Dmitri Mendeléyev, creador de la tabla periódica. Solo se produce átomo por átomo en aceleradores; es objeto exclusivo de investigación en física nuclear.'
  },
  {
    atomicNumber: 102,
    symbol: 'No',
    name: 'Nobelio',
    atomicMass: 259,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f¹⁴ 7s²',
    standardState: 'solid',
    meltingPoint: 1100,
    boilingPoint: null,
    summary: 'Actínido sintético bautizado en honor a Alfred Nobel. Sus isótopos más estables tienen vidas medias de minutos; su síntesis y estudio son puramente de interés en física nuclear fundamental.'
  },
  {
    atomicNumber: 103,
    symbol: 'Lr',
    name: 'Lawrencio',
    atomicMass: 266,
    category: 'actinido',
    period: 7,
    group: null,
    electronConfiguration: '[Rn] 5f¹⁴ 7s² 7p¹',
    standardState: 'solid',
    meltingPoint: 1900,
    boilingPoint: null,
    summary: 'El último actínido, bautizado en honor a Ernest Lawrence, inventor del ciclotrón. Solo se ha sintetizado en cantidades de átomos individuales y se estudia exclusivamente en el contexto de la física nuclear teórica y experimental.'
  },
  {
    atomicNumber: 104,
    symbol: 'Rf',
    name: 'Rutherfordio',
    atomicMass: 267,
    category: 'metal-transicion',
    period: 7,
    group: 4,
    electronConfiguration: '[Rn] 5f¹⁴ 6d² 7s²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Primer elemento superpesado transactínido, bautizado en honor a Ernest Rutherford. Solo se produce en aceleradores de partículas en cantidades de átomos individuales; su química se investiga para comprender tendencias periódicas.'
  },
  {
    atomicNumber: 105,
    symbol: 'Db',
    name: 'Dubnio',
    atomicMass: 268,
    category: 'metal-transicion',
    period: 7,
    group: 5,
    electronConfiguration: '[Rn] 5f¹⁴ 6d³ 7s²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor a la ciudad de Dubna, sede del Instituto Conjunto de Investigación Nuclear. Se produce en cantidades de átomos y se estudia su comportamiento químico.'
  },
  {
    atomicNumber: 106,
    symbol: 'Sg',
    name: 'Seaborgio',
    atomicMass: 269,
    category: 'metal-transicion',
    period: 7,
    group: 6,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁴ 7s²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado bautizado en honor al premio Nobel Glenn T. Seaborg. Es notable por ser el primer elemento nombrado en vida de su homenajeado; se sintetiza átomo a átomo en aceleradores.'
  },
  {
    atomicNumber: 107,
    symbol: 'Bh',
    name: 'Bohrio',
    atomicMass: 270,
    category: 'metal-transicion',
    period: 7,
    group: 7,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁵ 7s²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor a Niels Bohr. Sus isótopos más estables tienen vidas medias de segundos; se produce en cantidades mínimas para estudios de química nuclear relativista.'
  },
  {
    atomicNumber: 108,
    symbol: 'Hs',
    name: 'Hasio',
    atomicMass: 277,
    category: 'metal-transicion',
    period: 7,
    group: 8,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁶ 7s²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor al estado alemán de Hesse. Se han sintetizado solo unos pocos átomos; su óxido HsO₄ fue estudiado por su analogía con el tetróxido de osmio.'
  },
  {
    atomicNumber: 109,
    symbol: 'Mt',
    name: 'Meitnerio',
    atomicMass: 278,
    category: 'metal-transicion',
    period: 7,
    group: 9,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁷ 7s²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor a la física Lise Meitner, quien contribuyó al descubrimiento de la fisión nuclear. Solo se conocen unos pocos átomos sintetizados.'
  },
  {
    atomicNumber: 110,
    symbol: 'Ds',
    name: 'Darmstadtio',
    atomicMass: 281,
    category: 'metal-transicion',
    period: 7,
    group: 10,
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁸ 7s²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor a la ciudad de Darmstadt, Alemania, sede del GSI. Sus isótopos más estables tienen vidas medias de microsegundos; se estudia en el límite de la estabilidad nuclear.'
  },
  {
    atomicNumber: 111,
    symbol: 'Rg',
    name: 'Roentgenio',
    atomicMass: 282,
    category: 'metal-transicion',
    period: 7,
    group: 11,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s¹',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor a Wilhelm Röntgen, descubridor de los rayos X. Solo se han producido unos pocos átomos en aceleradores de partículas para investigación nuclear.'
  },
  {
    atomicNumber: 112,
    symbol: 'Cn',
    name: 'Copernicio',
    atomicMass: 285,
    category: 'metal-transicion',
    period: 7,
    group: 12,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',
    standardState: 'gas',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor a Nicolás Copérnico. Se predice que podría comportarse más como un gas noble que como un metal por efectos relativistas en su capa de valencia.'
  },
  {
    atomicNumber: 113,
    symbol: 'Nh',
    name: 'Nihonio',
    atomicMass: 286,
    category: 'metal-post-transicion',
    period: 7,
    group: 13,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Primer elemento descubierto en Asia, sintetizado en Japón y cuyo nombre proviene del japonés "nihon" (Japón). Solo se han observado unos pocos átomos durante experimentos de fusión nuclear de 2004.'
  },
  {
    atomicNumber: 114,
    symbol: 'Fl',
    name: 'Flerovio',
    atomicMass: 289,
    category: 'metal-post-transicion',
    period: 7,
    group: 14,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor al Laboratorio Nuclear Flerov de Dubna. Pertenece al grupo del carbono y se predice que podría tener propiedades inusuales por efectos relativistas.'
  },
  {
    atomicNumber: 115,
    symbol: 'Mc',
    name: 'Moscovio',
    atomicMass: 290,
    category: 'metal-post-transicion',
    period: 7,
    group: 15,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor a la región de Moscú, Rusia. Se sintetizó en 2003 en el JINR de Dubna; sus átomos son tan inestables que se desintegran en milisegundos.'
  },
  {
    atomicNumber: 116,
    symbol: 'Lv',
    name: 'Livermorio',
    atomicMass: 293,
    category: 'metal-post-transicion',
    period: 7,
    group: 16,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor al Laboratorio Nacional Lawrence Livermore de California. Se creó en colaboración entre el JINR ruso y el LLNL estadounidense en 2000.'
  },
  {
    atomicNumber: 117,
    symbol: 'Ts',
    name: 'Teneso',
    atomicMass: 294,
    category: 'halogeno',
    period: 7,
    group: 17,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
    standardState: 'solid',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'Elemento superpesado sintético bautizado en honor al estado de Tennessee, EE.UU., por sus instituciones colaboradoras en su síntesis. Solo se han observado unos 50 átomos desde su primera síntesis en 2010.'
  },
  {
    atomicNumber: 118,
    symbol: 'Og',
    name: 'Oganesón',
    atomicMass: 294,
    category: 'gas-noble',
    period: 7,
    group: 18,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
    standardState: 'unknown',
    meltingPoint: null,
    boilingPoint: null,
    summary: 'El elemento más pesado conocido, sintetizado en el JINR de Dubna en 2002. Bautizado en honor al físico Yuri Oganessian; los cálculos relativistas predicen que podría no comportarse como un gas noble.'
  }
];
