quarkus.application.name=account-catalog-data
quarkus.http.port=8080

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/microbanco
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# JPA / Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# OpenAPI
mp.openapi.extensions.smallrye.info.title=Account Catalog Data API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Microservicio bancario para gestión de cuentas y transferencias

# Native
quarkus.native.additional-build-args=--enable-all-security-services
